- hosts: masters
  become: yes
  tasks:
    - name: Create a new database with name 'altamar'
      community.mysql.mysql_db:
        check_implicit_admin: yes
        login_user: root
        login_password: -----====>SetR00tPa$$wordH3r3!!!<====-----
        name: "{{ database_name }}"
        state: present

    - name: Create user with password, all database privileges and 'WITH GRANT OPTION' in altamar
      community.mysql.mysql_user:
        state: present
        name: "{{ database_name }}"
        password: "{{ database_password }}"
        priv:
          'altamar.*': 'ALL,GRANT'
#          'db2.*': 'ALL,GRANT'
