- hosts: masters
  become: yes
  tasks:
    - name: create the '{{user}}' user
      user: name="{{app_name}}" append=yes state=present createhome=yes shell=/bin/bash

    - name: allow '{{user}}' to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        line: '{{app_name}} ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: set up authorized keys for the '{{ user }}' user
      authorized_key: user="{{user}}" key="{{item}}"
      with_file:
        - ~/.ssh/id_rsa.pub

    - name: Update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

