# This is a basic workflow to help you get started with Actions

name: Django application build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      # - name: psycopg2 prerequisites
      #   run: sudo apt-get install python-dev libpq-dev
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          
      - name: Setup flake8 annotations
        uses: rbialon/flake8-annotations@v1

      - name: Run migrations
        run: python backend/manage.py migrate
        
      - name: Lint with flake8
        run: |
          pip install flake8
          # stop the build if there are Python syntax errors or undefined names
          flake8 ./backend
        
  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build
    
  #   steps:
  #     - uses: actions/checkout@v1

  #     - name: install ansible
  #       run: | 
  #         sudo apt-get install python-dev libpq-dev
  #         sudo apt install software-properties-common
  #         sudo apt-add-repository --yes --update ppa:ansible/ansible
  #         sudo apt install ansible

  #     - name: executing remote ssh commands using password
  #       uses: appleboy/ssh-action@master
  #       with:
  #         host: expensescontrol.franedurios.com
  #         username: expenses_control
  #         key: ${{ secrets.PRIVATE_KEY }}
  #         script: whoami      
  
  #     - name: Run playbook
  #       uses: dawidd6/action-ansible-playbook@v2
  #       with:
  #         playbook: ./ops/deploy.yml
  #         key: ${{secrets.PRIVATE_KEY}}
  #         options: |
  #           -i ./ops/hosts
  #           -u expenses_control
  #           --extra-vars hello=there
  #           --verbose

        
